# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YilJhkt6TnPyaLXcqkCv5K3IcOdOx-AZ

# **Tokenizer**
"""

import numpy as np
docs=['go india',
      'india india'
      'hip hip hurray'
      'jeetega bhai india jeetega',
      'bharat mata ki jai',
      'kohli kohli',
      'sachin sachin',
      'dhoni dhoni',
      'modi ji ki jai',
      'inquilab zindabad'
      ]

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

tokenizer.fit_on_texts(docs)

tokenizer.word_index

tokenizer.document_count

sequences=tokenizer.texts_to_sequences(docs)
sequences

from keras.utils import pad_sequences

sequences=pad_sequences(sequences,padding='post')

sequences

model=Sequential()
model.add(Embedding(20,output_dim=2,input_length=5))
model.summary()

model.compile('adam','accuracy')

pred=model.predict(sequences)
print(pred)

"""# **sentiment** **analysis**"""

from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Input,Dense,SimpleRNN,Embedding,Flatten

(X_train,y_train),(X_test,y_test)=imdb.load_data()

X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

X_train

print("X_train max:", X_train.max())
print("X_test max:", X_test.max())

print("X_train min:", X_train.min())
print("X_test min:", X_test.min())

model = Sequential()

model.add(Input(shape=(50,)))
model.add(Embedding(input_dim=88586, output_dim=2))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

history = model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))